"""dates of user login and resgister

Revision ID: 3c939abe52b6
Revises: a483c7a45a88
Create Date: 2025-12-19 11:09:48.102708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c939abe52b6'
down_revision: Union[str, Sequence[str], None] = 'a483c7a45a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
