"""migration3

Revision ID: 73d7849b4bac
Revises: f5dcd050e91f
Create Date: 2025-12-20 18:19:54.254556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d7849b4bac'
down_revision: Union[str, Sequence[str], None] = 'f5dcd050e91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('vates_amount', sa.Integer(), nullable=True))
    op.add_column('list', sa.Column('created_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list', 'created_at')
    op.drop_column('film', 'vates_amount')
    # ### end Alembic commands ###
