"""migration2

Revision ID: f5dcd050e91f
Revises: 3c939abe52b6
Create Date: 2025-12-20 18:17:00.518087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5dcd050e91f'
down_revision: Union[str, Sequence[str], None] = '3c939abe52b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'country', ['country_name'])
    op.add_column('user', sa.Column('logged_out_at', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('logged_out_at2', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'logged_out_at2')
    op.drop_column('user', 'logged_out_at')
    op.drop_constraint(None, 'country', type_='unique')
    # ### end Alembic commands ###
